version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - ./api/.env
    ports:
      - 5000:5000
    volumes:
      - ./api/:/src/app
    depends_on:
      - db
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: front
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./client/:/src/app
      - /src/app/node_modules
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=mysqldatabase
