GET_ROOMS_QUERY = ("select "
                        "r.id, "
                        "case when r.is_group is true then r.name else u.name end as name, "
                        "r.latest_message "
                    "from "
                        "mysqldatabase.participants p1 "
                    "inner join "
                        "mysqldatabase.participants p2 "
                    "on "
                        "p1.room_id = p2.room_id "
                    "inner join "
                        "mysqldatabase.rooms r "
                    "on "
                        "p1.room_id = r.id "
                    "inner join "
                        "users u "
                    "on "
                        "p2.user_id = u.id "
                    "where "
                        "p1.user_id <> p2.user_id AND p1.user_id = :user_id;");


GET_MESSAGES_BY_ME_AND_FRIEND_ID_QUERY = ("select "
                                               "m.id, u.id, u.name, m.content "
                                          "from "
                                          	   "mysqldatabase.messages m "
                                          "inner join "
                                               "mysqldatabase.users u "
                                          "on "
                                               "m.user_id = u.id "
                                          "where "
                                          	   "room_id = ( "
                                          "select "
                                          	   "p1.room_id "
                                          "from "
                                          	   "mysqldatabase.participants p1 "
                                          "inner join "
                                          	    "mysqldatabase.participants p2 "
                                          "on "
                                          	    "p1.room_id = p2.room_id "
                                          "where "
                                                "p1.user_id = :user_id and p2.user_id = :friend_id;");