GET_ROOMS_QUERY = ("select "
                        "case when r.is_group is true then r.name else u.name end as name, "
                        "r.latest_message "
                    "from "
                        "mysqldatabase.participants p1 "
                    "inner join "
                        "mysqldatabase.participants p2 "
                    "on "
                        "p1.room_id = p2.room_id "
                    "inner join "
                        "mysqldatabase.rooms r "
                    "on "
                        "p1.room_id = r.id "
                    "inner join "
                        "users u "
                    "on "
                        "p2.user_id = u.id "
                    "where "
                        "p1.user_id <> p2.user_id AND p1.user_id = :user_id;");